### ISSUE TITLE
The button does not take the proper appearance in the current Firefox.

### ISSUE THREAD

**Issue by johngraciliano** [drsjb80/personaswitcher#11]
Thank you for such excellent extension.

Current **Firefox**'s **_default**_ theme (and others) do not show the button properly*, especially when placed in the main (_hambuger_) menu.  To fix this problem, the `toolbarbutton` with attribute `id = "personaswitcher-button"` needs to include the attribute `class = "toolbarbutton-1"` (the syntax may need correction).  This simple fix can greatly improve the extension.

---

*I mean, style rules that should apply to the button are ignored, so it breaks the appearance of the theme.

**Comment by drsjb80** [comment]
That was suggested by another user, and is in the current alpha version. I'm working on getting a version pushed out. Thanks very much!

**Comment by johngraciliano** [comment]
Then just in case you have not done it, you may also want to consider adding the css rules:
```css
toolbarpaletteitem[place="palette"] > #personaswitcher-button,
#personaswitcher-button[cui-areatype="menu-panel"]{
  list-style-image: url("chrome://personaswitcher/skin/PersonaSwitcher32.png");
}
```
(to use the larger icon in the menu and the customization area) and
```css
 toolbarpaletteitem[place="palette"] > #personaswitcher-button > .toolbarbutton-menu-dropmarker {
  display: none;
}
```
(to hide the drop down marker in the customization area).

p.s. (_Out of topic_) You have an good show of papers in you page...  Nice to meet you.
